spring:
  application:
    name: "gatewayServer"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayServer"
    description: "Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      bankSystem:
        gatewayServer: DEBUG

