spring:
  application:
      name: "eurekaServer"
  config:
    import: "optional:configserver:http://localhost:8071/"
management:
  endpoint:
    health:
      probes:
        enabled: true
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"