spring:
  application:
    name: "configserver"
  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/said-nasser2001/Bank-System-config"
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
server:
  port: 8071


management:
  endpoint:
    health:
      probes:
        enabled: true
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"